apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vbyom1soc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vbyom1soc-go 
  name: vbyom1soc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vbyom1soc-go 
